
title: Lucas Zientek
email: lucas@zientek.fr
description: >-
  Je m'appelle Lucas Zientek je suis développeur fullstack du frontend à l'ops.
  Passionné de dev, d'automatisation et de nouvelles technologies je vous partage sur ce blog mes trouvailles.
baseurl: ""
url: "https://lzientek.fr"
twitter_username: lucas42_
author: lzientek
copyright: Copyright © 1994-2020
github_username: lzientek

# Build settings
theme: jekyll-theme-yat
plugins:
  - jekyll-feed

lang: "fr"  # default lang is en
yat:
  date_format: "%d/%m/%C"

# Google analytics
google_analytics: G-CYSQ8K0L6C

# Gitment comments
gitment:
  username: "lzientek"
  repo: "blog"
  client_id: "e08b27202d11da29003c"
  client_secret: "2c8ffa0e011df4c406a38d7bde28d39e5046e0a4"
  # redirect_uri: "http://localhost:4000"   # If you use a custom domain name

header_pages:
  - index.markdown
  #  - archives.html
  # - categories.html
  # - tags.markdown
  - about.markdown